# Generated by Django 4.1.5 on 2023-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stdNum',
            field=models.IntegerField(verbose_name='Student Number'),
        ),
    ]
