# Generated by Django 4.1.5 on 2023-01-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_stdnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(default='A picture of the student', upload_to='', verbose_name='Picture'),
        ),
    ]
